_BASE_: "Base-cod10k-contrast-hed-CIS.yaml"
MODEL:
  WEIGHTS: ""  # download weights from https://github.com/microsoft/Swin-Transformer
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TEST: 800
DATALOADER:
    NUM_WORKERS: 0